# Generated by Django 4.1.7 on 2023-03-05 13:55

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote1', models.TextField(blank=True)),
                ('paragraph1', models.TextField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('image1_description', models.TextField(blank=True)),
                ('quote2', models.TextField(blank=True)),
                ('paragraph2', models.TextField()),
                ('image2', models.ImageField(upload_to='images/')),
                ('image2_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionsPageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('occurence', models.CharField(choices=[('past', 'Past'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='past', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image_description', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewslettersSuscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('print_medium', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsPageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content_text', models.TextField()),
                ('content_link', models.URLField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.models.get_uuid, editable=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallerycategory')),
            ],
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallerysection'),
        ),
    ]
