# Generated by Django 4.1.7 on 2023-03-05 14:12

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.models.get_uuid, editable=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallerycategory')),
            ],
        ),
    ]
