# Generated by Django 4.1.7 on 2023-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationspageitem',
            name='content_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicationspageitem',
            name='date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='publicationspageitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
